In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd 
import seaborn as sns
# Keras
from keras.models import Sequential
from keras.layers import Dense

from tensorflow.keras.optimizers import SGD, Adam, Adadelta, RMSprop
import keras.backend as K
# Train-Test
from sklearn.model_selection import train_test_split
# Scaling data
from sklearn.preprocessing import StandardScaler
# Classification Report
from sklearn.metrics import classification_report
from keras.utils.np_utils import to_categorical

In [16]:
df = pd.read_csv('data.csv')
df.head()

,group,samples,X1.Methylnicotinamide,X2.Hydroxybutyrate,X2.Hydroxyisobutyrate,X2.Oxoisocaproate,X2.Phenylpropionate,X3.Hydroxyisovalerate,X3.Indoxylsulfate,X3.Methyl.2.oxovalerate,...,Tryptophan,Tyramine,Urea,Valine,Xylose,cis.Aconitate,myo.Inositol,sn.Glycero.3.phosphocholine,trans.Aconitate,pi.Methylhistidine
0,0,control,270.535349,71.516142,16.755210,0.568914,10.625255,10.216592,20.841847,8.173273,...,13.077237,28.197793,2742.133224,6.538619,1.796634,23.702493,2.328479,13.485901,2.784256,71.516142
1,1,sample 1,58.225953,114.366679,23.632572,4.491258,10.158798,13.687644,94.744159,14.703523,...,12.832166,15.077795,7261.401914,4.918997,13.046035,42.453082,24.648452,7.111159,6.416083,111.372507
2,2,sample 2,26.983984,29.868686,11.839298,4.837886,3.215241,2.854653,102.767511,5.468914,...,8.894498,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446
3,2,sample 3,46.237843,44.531650,19.621225,5.203890,4.265484,5.118580,19.365296,8.360348,...,9.469374,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924
4,3,sample 4,29.122282,69.737744,16.788139,8.316203,10.216159,13.486576,28.032144,9.344048,...,4.827758,16.756992,10053.043040,17.099608,2.121825,29.464898,81.293216,4.360556,9.281754,200.492120

In [17]:
df = df.T

In [18]:
new_df = df.drop(['group','samples'])
new_df[2] = (new_df[2] +new_df[3])/2
new_df[4] = (new_df[4] +new_df[5])/2
new_df = new_df.drop([3, 5], axis=1)
new_df.head()

                                0           1          2          4
X1.Methylnicotinamide  270.535349   58.225953  36.610914  24.338604
X2.Hydroxybutyrate      71.516142  114.366679  37.200168  43.561199
X2.Hydroxyisobutyrate    16.75521   23.632572  15.730262   11.40771
X2.Oxoisocaproate        0.568914    4.491258   5.020888   4.950869
X2.Phenylpropionate     10.625255   10.158798   3.740362   6.013296

In [19]:
new_df.rename(columns = {0:'group_0', 1:'group_1',
                              2:'group_2',4:'group_3'}, inplace = True)
new_df.head()

                          group_0     group_1    group_2    group_3
X1.Methylnicotinamide  270.535349   58.225953  36.610914  24.338604
X2.Hydroxybutyrate      71.516142  114.366679  37.200168  43.561199
X2.Hydroxyisobutyrate    16.75521   23.632572  15.730262   11.40771
X2.Oxoisocaproate        0.568914    4.491258   5.020888   4.950869
X2.Phenylpropionate     10.625255   10.158798   3.740362   6.013296

In [20]:
metabolites = new_df.index
metabolites = list(metabolites)
Metabolites = [4*metabolites]
#print(Metabolites[0])
group_0 = list(new_df['group_0'])
group_1 = list(new_df['group_1'])
group_2 = list(new_df['group_2'])
group_3 = list(new_df['group_3'])
concentration = []
concentration.extend(group_0)
concentration.extend(group_1)
concentration.extend(group_2)
concentration.extend(group_3)

def group_label(group,val):
    label = []
    for i in range(0,len(group)):
        label.append(val)
    return label
group = []
group = group_label(group_0,0)
group.extend(group_label(group_1,1))
group.extend(group_label(group_2,2))
group.extend(group_label(group_3,3))
group

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3]

In [21]:
concn = [round(item) for item in concentration ]
print(concn)

[271, 72, 17, 1, 11, 10, 21, 8, 23, 47, 128, 47, 175, 9, 132, 27, 444, 34, 76, 288, 161, 33, 21, 305, 7, 4, 2429, 51, 1081, 7, 104, 3, 5, 5, 10, 2, 358, 45, 3, 476, 16, 0, 78, 13, 28, 2742, 7, 2, 24, 2, 13, 3, 72, 58, 114, 24, 4, 10, 14, 95, 15, 5, 143, 17, 75, 931, 23, 41, 24, 690, 47, 51, 177, 48, 26, 62, 10, 7, 3, 1230, 64, 1676, 20, 10, 4, 8, 21, 59, 3, 12, 7, 34, 65, 34, 5, 10, 13, 15, 7261, 5, 13, 42, 25, 7, 6, 111, 37, 37, 16, 5, 4, 4, 61, 7, 15, 22, 16, 43, 1137, 18, 44, 14, 694, 68, 12, 64, 39, 15, 43, 84, 14, 1, 471, 131, 426, 1, 7, 3, 10, 7, 117, 1, 5, 41, 114, 208, 47, 7, 11, 9, 42, 5798, 3, 10, 76, 22, 8, 7, 113, 24, 44, 11, 5, 6, 10, 17, 6, 25, 68, 6, 76, 850, 40, 77, 13, 24, 26, 18, 211, 33, 48, 44, 20, 15, 2, 32, 90, 1030, 3, 9, 7, 9, 10, 101, 1, 538, 32, 6, 655, 11, 6, 4, 3, 18, 6857, 9, 2, 17, 44, 2, 6, 444]

In [22]:
def value_10prcnt(value):
    bound_value = round(0.1 * value)
    lower_bound = value - bound_value
    upper_bound = value + bound_value
    value_range = []
    for i in range(lower_bound,(upper_bound+1)):
        value_range.append(i)
    return value_range

In [23]:
def value_range_generator(value,length):
    value_range = []
    for i in range(0,length):
        value_range.append(value)
    return value_range

In [24]:
concentration_range = []
Metabolites_range = []
group_label = []


for i in range(0,len(concn)):
    concn_range = value_10prcnt(concn[i])
    temp_length = len(concn_range)
    metabolite_range = value_range_generator(Metabolites[0][i],temp_length)
    group_range = value_range_generator(group[i],temp_length)
    concentration_range.extend(concn_range)
    Metabolites_range.extend(metabolite_range)
    group_label.extend(group_range)
    

print(len(concentration_range))
print(len(Metabolites_range))
print(len(group_label))

9258
9258
9258

In [25]:
dataset = pd.DataFrame(list(zip(Metabolites_range, concentration_range)),
               columns =['Metabolites', 'Concentration'])

In [26]:
dataset['Group']=group_label

In [27]:
print(dataset.head())
print(dataset.shape)

             Metabolites  Concentration  Group
0  X1.Methylnicotinamide            244      0
1  X1.Methylnicotinamide            245      0
2  X1.Methylnicotinamide            246      0
3  X1.Methylnicotinamide            247      0
4  X1.Methylnicotinamide            248      0
(9258, 3)

In [81]:
# saving the dataframe
#dataset.to_csv('processed_data.csv')

Model Training

In [29]:
metabolites_cat = pd.get_dummies(dataset['Metabolites'])

In [30]:
metabolites_cat

,Acetate,Acetone,Alanine,Allantoin,Betaine,Carnitine,Choline,Creatine,Dimethylamine,Formate,...,X3.Hydroxyisovalerate,X3.Indoxylsulfate,X3.Methyl.2.oxovalerate,X4.Hydroxyphenylacetate,Xylose,cis.Aconitate,myo.Inositol,pi.Methylhistidine,sn.Glycero.3.phosphocholine,trans.Aconitate
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9254,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9255,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9256,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9257,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [31]:
new_dataset = pd.concat([dataset,metabolites_cat],axis=1)

In [32]:
new_dataset=new_dataset.drop(['Metabolites'],axis=1)

In [33]:
new_dataset

,Concentration,Group,Acetate,Acetone,Alanine,Allantoin,Betaine,Carnitine,Choline,Creatine,...,X3.Hydroxyisovalerate,X3.Indoxylsulfate,X3.Methyl.2.oxovalerate,X4.Hydroxyphenylacetate,Xylose,cis.Aconitate,myo.Inositol,pi.Methylhistidine,sn.Glycero.3.phosphocholine,trans.Aconitate
0,244,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,245,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,246,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,247,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,248,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9253,484,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9254,485,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9255,486,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9256,487,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9257,488,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [34]:
X = new_dataset.drop(['Group'],axis = 1)
y = new_dataset['Group']
y

0       0
1       0
2       0
3       0
4       0
       ..
9253    3
9254    3
9255    3
9256    3
9257    3
Name: Group, Length: 9258, dtype: int64

In [94]:
X_scaled = X.copy()
X_scaled["Concentration"] = X_scaled["Concentration"] /X_scaled["Concentration"].abs().max()
list(X_scaled.iloc[0,:])

[0.030549643170151495,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [36]:
y_cat = to_categorical(y)

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_cat, test_size=0.2)

In [67]:
# Feature Scaling
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [68]:
model = Sequential()
model.add(Dense(60, input_shape = (54,), activation = "relu"))
model.add(Dense(15, activation = "relu"))
#model.add(Dropout(0.2))
model.add(Dense(4, activation = "softmax"))
model.compile(Adam(lr = 0.01), "categorical_crossentropy", metrics = ["accuracy"])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 60)                3300

 dense_10 (Dense)            (None, 15)                915

 dense_11 (Dense)            (None, 4)                 64

=================================================================
Total params: 4,279
Trainable params: 4,279
Non-trainable params: 0
_________________________________________________________________

In [74]:
model.fit(X_train, y_train, verbose=1, epochs=100)

Epoch 1/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5354 - accuracy: 0.7066
Epoch 2/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5197 - accuracy: 0.7082
Epoch 3/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5202 - accuracy: 0.7059
Epoch 4/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5141 - accuracy: 0.7077
Epoch 5/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5140 - accuracy: 0.7096
Epoch 6/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5176 - accuracy: 0.7032
Epoch 7/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5177 - accuracy: 0.7075
Epoch 8/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5219 - accuracy: 0.7048
Epoch 9/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5121 - accuracy: 0.7066
Epoch 10/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5382 - accuracy: 0.7036
Epoch 11/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5199 - accuracy: 0.7029
Epoch 12/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5250 - accuracy: 0.7066
Epoch 13/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5149 - accuracy: 0.7110
Epoch 14/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5169 - accuracy: 0.7094
Epoch 15/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5180 - accuracy: 0.7090
Epoch 16/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5109 - accuracy: 0.7035
Epoch 17/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5293 - accuracy: 0.6984
Epoch 18/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5085 - accuracy: 0.7108
Epoch 19/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5249 - accuracy: 0.7013
Epoch 20/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5100 - accuracy: 0.7117
Epoch 21/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5167 - accuracy: 0.7027
Epoch 22/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5133 - accuracy: 0.7013
Epoch 23/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5104 - accuracy: 0.7046
Epoch 24/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5122 - accuracy: 0.7078
Epoch 25/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5090 - accuracy: 0.7024
Epoch 26/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5181 - accuracy: 0.7027
Epoch 27/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5194 - accuracy: 0.7056
Epoch 28/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5123 - accuracy: 0.7062
Epoch 29/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5156 - accuracy: 0.7031
Epoch 30/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5335 - accuracy: 0.7032
Epoch 31/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5162 - accuracy: 0.7071
Epoch 32/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5210 - accuracy: 0.7033
Epoch 33/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5129 - accuracy: 0.7062
Epoch 34/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5058 - accuracy: 0.7051
Epoch 35/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5059 - accuracy: 0.7050
Epoch 36/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5096 - accuracy: 0.7008
Epoch 37/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5056 - accuracy: 0.7089
Epoch 38/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5173 - accuracy: 0.7065
Epoch 39/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5160 - accuracy: 0.7024
Epoch 40/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5129 - accuracy: 0.7077
Epoch 41/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5125 - accuracy: 0.7094
Epoch 42/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5233 - accuracy: 0.7054
Epoch 43/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5063 - accuracy: 0.7046
Epoch 44/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5093 - accuracy: 0.7042
Epoch 45/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5077 - accuracy: 0.7051
Epoch 46/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5070 - accuracy: 0.7090
Epoch 47/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5182 - accuracy: 0.6988
Epoch 48/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5136 - accuracy: 0.7078
Epoch 49/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5074 - accuracy: 0.7067
Epoch 50/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5082 - accuracy: 0.7032
Epoch 51/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5102 - accuracy: 0.7070
Epoch 52/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5170 - accuracy: 0.7059
Epoch 53/100
232/232 [==============================] - 0s 1ms/step - loss: 0.4996 - accuracy: 0.7056
Epoch 54/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5038 - accuracy: 0.7035
Epoch 55/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5117 - accuracy: 0.7050
Epoch 56/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5137 - accuracy: 0.7087
Epoch 57/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5125 - accuracy: 0.7044
Epoch 58/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5160 - accuracy: 0.7021
Epoch 59/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5120 - accuracy: 0.7029
Epoch 60/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5110 - accuracy: 0.7069
Epoch 61/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5073 - accuracy: 0.7094
Epoch 62/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5104 - accuracy: 0.7077
Epoch 63/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5149 - accuracy: 0.7043
Epoch 64/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5143 - accuracy: 0.7058
Epoch 65/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5104 - accuracy: 0.7021
Epoch 66/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5094 - accuracy: 0.7015
Epoch 67/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5220 - accuracy: 0.7031
Epoch 68/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5126 - accuracy: 0.7038
Epoch 69/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5133 - accuracy: 0.7021
Epoch 70/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5091 - accuracy: 0.7082
Epoch 71/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5160 - accuracy: 0.7069
Epoch 72/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5118 - accuracy: 0.7071
Epoch 73/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5080 - accuracy: 0.7121
Epoch 74/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5177 - accuracy: 0.7074
Epoch 75/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5100 - accuracy: 0.7082
Epoch 76/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5151 - accuracy: 0.7000
Epoch 77/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5087 - accuracy: 0.7106
Epoch 78/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5219 - accuracy: 0.6986
Epoch 79/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5103 - accuracy: 0.7052
Epoch 80/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5146 - accuracy: 0.7001
Epoch 81/100

232/232 [==============================] - 0s 1ms/step - loss: 0.5081 - accuracy: 0.7043
Epoch 82/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5127 - accuracy: 0.7043
Epoch 83/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5113 - accuracy: 0.7055
Epoch 84/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5228 - accuracy: 0.6994
Epoch 85/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5193 - accuracy: 0.7056
Epoch 86/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5173 - accuracy: 0.7083
Epoch 87/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5077 - accuracy: 0.7073
Epoch 88/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5041 - accuracy: 0.7109
Epoch 89/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5155 - accuracy: 0.7052
Epoch 90/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5053 - accuracy: 0.7042
Epoch 91/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5312 - accuracy: 0.6984
Epoch 92/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5273 - accuracy: 0.6925
Epoch 93/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5272 - accuracy: 0.6966
Epoch 94/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5398 - accuracy: 0.6907
Epoch 95/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5309 - accuracy: 0.7015
Epoch 96/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5286 - accuracy: 0.6959
Epoch 97/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5269 - accuracy: 0.6954
Epoch 98/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5284 - accuracy: 0.6978
Epoch 99/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5402 - accuracy: 0.6894
Epoch 100/100
232/232 [==============================] - 0s 1ms/step - loss: 0.5286 - accuracy: 0.6993

In [70]:
y_predict = np.argmax(model.predict(X_test), axis=-1)

In [87]:
print(y_predict[1])
print(y_test[1])

1
[0. 1. 0. 0.]

In [97]:
y_pred = model.predict(pd.DataFrame([[0.030549643170151495,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]]))

In [99]:
y_pred = np.argmax(y_pred, axis=-1)

In [101]:
y_pred[0]

0